version: '3'
services:
  app:
    image: docker-spring-boot
    ports:
    - "8085:8085"
    depends_on:
    - mypostgres
  mypostgres:
    image: ghusta/postgres-world-db:2.4
    container_name: mypostgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=world123
     - POSTGRES_USER=world
     - POSTGRES_DB=world-db